### ISSUE TITLE
Kleine anpassung an tonies_nfc_converter.py

### ISSUE THREAD

**Issue by SamNitro** [Fabunator/flipper-tonies-nfc-converter#2]
Hallo als erstes danke für das Python Script und sorry das ich alles auf Deutsch schreibe.
Vorweg ich kann nicht programmieren..... was ich mir hier geändert habe war mittels ChatGPT.

Ich wollte das er mir die *.nfc Dateien auch ändert wenn wiklich nur die UID und Data Content enthalten sind.

Könnt ihr mir sagen ob es nachteile mit dem Code gibt? Habe bisher nur im testorder experimentiert.
```

"""
This module provides functionality for converting old nfc tonies files from the flipper zero
to the current version 4 of the NFC files for SLIX Tags

"""

import os
import sys
from tkinter import Tk
from tkinter.filedialog import askdirectory, askopenfilename
from pathlib import Path
import jinja2

script_path = Path(sys.argv[0]).absolute()
currdir = script_path.parents[0]

def extract_uid_and_data_content(file_path):
    uid = None
    data_content = None

    with open(file_path, 'r', encoding='UTF-8') as nfc_file:
        for line in nfc_file:
            if line.startswith("#"):
                continue
            # Strip newline characters and split the line into key and value
            parts = line.strip().split(': ', 1)
            if len(parts) != 2:
                continue
            key, value = parts
            
            # Check if the line contains the UID or DataContent
            if key == 'UID':
                uid = value
            elif key == 'Data Content':
                data_content = value

    return {'uid': uid, 'data': data_content}

root = Tk()
root.withdraw() # use to hide tkinter window
template_file = askopenfilename(parent=root, initialdir=currdir, title='Select Template File')
tonie_file_dir = askdirectory(parent=root, initialdir=currdir, title='Select Tonies Folder')

with open(template_file, encoding='UTF-8') as file_:
    template = jinja2.Template(file_.read(), line_comment_prefix='{=', comment_start_string='{=', comment_end_string='=}')
    abs_count = 0
    for root, dirs, files in os.walk(tonie_file_dir):
        count = 0
        for file in files:
            if file.endswith(".nfc"):
                count += 1
                file_name = os.path.join(root, file)
                file_content = extract_uid_and_data_content(file_name)
                rendered_string = template.render(file_content)
                new_file = open(file_name, 'w', encoding='UTF-8')
                new_file.write(rendered_string)
                new_file.close()
        abs_count += count
    print(f"Done converting {abs_count} files")

```

Gruß Patrick

**Comment by Fabunator** [comment]
Hallo
ich habe den Grund für deine Anpassung noch nicht ganz verstanden, vielleicht kannst du ein Beispiel nennen mit dem es in der ursprünglichen Version nicht funktioniert hat. Denn im Grunde arbeitet der Code identisch.

`key, value = line.strip().split(': ')`
Teilt die Zeile und erwartet nur zwei Elemente. Dabei könnte einen Fehler auftreten, falls die Zeile aus mehr als einem oder keinem Trennzeichen besteht. Das sollte allerdings bei den *nfc Files nicht der Fall sein.

`parts = line.strip().split(': ', 1)`
fügt jetzt eine Bedingung ein, dass die Zeile nur genau einmal getrennt wird, egal wie viele Trennzeichen enthalten sind und speichert das Ergebnis in einer Liste unbestimmter Größe.

Bei regulären *nfc Files führt das dazu, dass `len(parts)` immer zwei ist und dadurch dasselbe Ergebnis liefert wie der ursprüngliche Code.

Falls in einer Zeile keine Trennzeichen vorhanden sind führt die Prüfung auf die Länge der Liste `len(parts) != 2` dazu, dass diese Zeilen übersprungen werden.

Die Änderung kann man zur Erhöhung der Stabilität des Codes bedenkenlos einfügen.
Ich kenne in den *nfc Files allerdings keine Stellen in denen diese Anpassung relevant wäre.

**Comment by SamNitro** [comment]
Habe jetzt selber nochmal getestet, wenn die datei mit einer leerzeile beginnt ging es nicht. Anfangs wollte ich wissen welche informationen benötigt werden.

**Comment by SamNitro** [comment]
Nach weiterem experemntieren Funktioniert folgende änderung für mich:
`            if line.startswith("#"):
                continue`
in
`            if line.startswith("#") or not line.strip():
                continue`
hier ist es egal wo eine leerzeile in der *.nfc datei ist,
wie gesagt alles leider nur mittels ChatGPT

**Comment by Fabunator** [comment]
Ich habe deine Vorschläge und noch andere Korrekturen aufgenommen und aktualisiert.

**Comment by SamNitro** [comment]
Ja funktioniert gut :)
mir gefällt auch, das man bei der auswahl der jinja2 datei jetzt einen filter nur für diese dateien hat.

Danke LG
